exclude: [
  ".rvmrc",
  ".rbenv-version",
  "README.md",
  "Rakefile",
  "changelog.md",
  "Gemfile",
  "Gemfile.lock",
  "*.log",
  "autoprefixer.yml",
  "docker-compose.yml",
  "Dockerfile"
]

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: Screenly
tagline: Digital Signage for the Raspberry Pi
description: Screenly is a digital signage software for the Raspberry Pi used by hundreds of companies to power over 10,000 screens around the world.
email: hello@screenly.io
image: "screenly-twitter.png"
image_url: "https://www.screenly.io/assets/img/screenly-twitter.png"
author:
  name: Screenly
  email: hello@screenly.io
  github: Screenly
  twitter: ScreenlyApp
  feedburner:
social:
  google: https://plus.google.com/+Screenlyapp
  facebook: https://www.facebook.com/Screenly/
  twitter: https://twitter.com/ScreenlyApp
  linkedin: https://www.linkedin.com/company-beta/10478856/
  github: https://github.com/orgs/Screenly/
  medium: https://news.screenly.io/
  youtube: https://www.youtube.com/c/screenlydigitalsignage


# JS Social
shares:
  - "twitter"
  - "facebook"
  - "googleplus"
  - "linkedin"

# Define the excerpt separator, used to determine which part of the blog post gets previewed
excerpt_separator: "<!--more-->"

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use site.url to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
# baseurl: ":8080" # the subpath of your site, e.g. /blog
production_url: https://www.screenly.io
url: https://www.screenly.io


# Markdown format
markdown: kramdown
highlighter: rouge

plugins:
  - "jekyll-last-modified-at"
  - "octopress-paginate"
  - "jekyll-sitemap"
  - "jekyll-assets"
  - "jekyll-minifier"

# docs http://www.rubydoc.info/gems/jekyll-assets/
assets:
  digest: true
  compress:
    css:  true
    js:   uglifier
  autoprefixer:
    browsers:
      - "> 1%"
      - "last 3 versions"
      - "IE > 9"
  prefix: "/assets"
  sources:
    - _assets/
    - _assets/js
    - _assets/css
    - _assets/javascript
    - _assets/stylesheets
    - _assets/img
    - _assets/fonts

tags_dir: pages/blog/tag

# Blog config
# paginate: 5
permalink: "/blog/:year/:month/:day/:title/"
# paginate_path: "/blog/page/:num/"