version: '3'
services:
  jekyll:
    build: .
    # command: jekyll build --watch # Without incremental allows better local dev troubleshooting
    command: jekyll build -V --watch --incremental --config _config.yml,_config_dev.yml
    volumes:
      - .:/usr/src/app
    environment:
      - JEKYLL_ENV=development
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - jekyll
